version: '3'

services:
  db:
    container_name: next-db
    image: postgres:latest
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  web:
    container_name: next-app
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - db

  pgadmin:
    container_name: next-db-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    depends_on:
      - db
